services:
  backend:
    image: stasya1/example-backend
    build:
      context: "server"
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - "server/.env"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
